name: Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.1.1'

      - name: Install dependencies
        run: meteor npm ci --ignore-scripts

      - name: Start Meteor App
        run: nohup meteor npm run start &

      - name: Install Wait Port
        run: npm install -g wait-port

      - name: Install Meteor Ping
        run: npm install -g meteor-ping

      - name: Wait Until Port 3000 Is Being Used
        run: wait-port 3000

      - name: Wait Until Meteor App is Up
        run: meteor-ping --connectTimeout 600000

      - name: Run Integration Tests
        run: ./scripts/integration-test.sh
