name: Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '2.1.1'

      - name: Install dependencies
        run: meteor npm ci --ignore-scripts

      - name: Start Meteor App
        run: meteor npm run start

      - name: Run Integration Tests
        run: ./scripts/integration-test.sh
